# The esdt_dir can be looked up at
# https://goldsmr4.gesdisc.eosdis.nasa.gov/data/

subdaily_vars = {'pr': {'esdt_dir': 'M2T1NXFLX.5.12.4',
                        'collection': 'tavg1_2d_flx_Nx',
                        'merra_name': 'PRECTOT',
                        'standard_name': 'precipitation_flux'},
                 'prmax': {'esdt_dir': 'M2SDNXSLV.5.12.4',
                           'collection': 'statD_2d_slv_Nx',
                           'merra_name': 'TPRECMAX',
                           'standard_name': 'precipitation_flux'},
                 'prc': {'esdt_dir': 'M2T1NXFLX.5.12.4',
                         'collection': 'tavg1_2d_flx_Nx',
                         'merra_name': 'PRECCON',
                         'standard_name': 'convective_precipitation_flux'},
                 'prsn': {'esdt_dir': 'M2T1NXFLX.5.12.4',
                          'collection': 'tavg1_2d_flx_Nx',
                          'merra_name': 'PRECSNO',
                          'standard_name': 'snowfall_flux'},
                 'tasmax': {'esdt_dir': 'M2SDNXSLV.5.12.4',
                            'collection': 'statD_2d_slv_Nx',
                            'merra_name': 'T2MMAX',
                            'standard_name': 'air_temperature'},
                 'tasmin': {'esdt_dir': 'M2SDNXSLV.5.12.4',
                            'collection': 'statD_2d_slv_Nx',
                            'merra_name': 'T2MMIN',
                            'standard_name': 'air_temperature'},
                 'uas': {'esdt_dir': 'M2I1NXASM.5.12.4',
                         'collection': 'inst1_2d_asm_Nx',
                         'merra_name': 'U10M',
                         'standard_name': 'eastward_wind'},
                 'vas': {'esdt_dir': 'M2I1NXASM.5.12.4',
                         'collection': 'inst1_2d_asm_Nx',
                         'merra_name': 'V10M',
                         'standard_name': 'northward_wind'}}
